# Generated by Django 3.1.3 on 2021-03-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=256)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transaction_status', models.CharField(default='PENDING', max_length=255)),
                ('credited_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='transactions.customer')),
                ('debited_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='transactions.customer')),
            ],
        ),
    ]
